// FALLBACK SNAPSHOT — sumber utama runtime: Firestore collection markets
const PINRANG_ALL_MARKETS = [
  {
    "id": "pasar-sentral-pinrang",
    "nama": "Pasar Sentral Pinrang",
    "namaAlternatif": "Pasar Sentral Kabupaten Pinrang",
    "slug": "pasar-sentral-pinrang",
    "kecamatan": "Watang Sawitto",
    "desaKelurahan": "Penrang",
    "alamat": "6J6X+56M, Jl. Kemuning, Penrang, Kec. Watang Sawitto, Kabupaten Pinrang, Sulawesi Selatan 91212, Indonesia",
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "Tinggi",
    "buktiOperasionalTerakhir": "Pemantauan harian harga Bapokting Disperindag ESDM 2026 & aktivitas distribusi aktif.",
    "klasifikasiHistoris": "Tipe A",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "UPTD Pasar Wilayah II",
    "statusVerifikasiUnitPengelola": "Terverifikasi Sesuai Nomenklatur",
    "hariPasar": [
      "Setiap hari"
    ],
    "jamOperasional": "05.30 – 17.30 WITA",
    "luasLahanM2": null,
    "jumlahKios": 786,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [
      "Beras",
      "Minyak Goreng",
      "Gula Pasir",
      "Daging Sapi & Ayam",
      "Cabai & Bawang",
      "Ikan Basah & Kering",
      "Tekstil & Pakaian"
    ],
    "fasilitas": [
      "Kantor Pengelola UPTD",
      "Pos Ukur Ulang Kemetrologian",
      "Musholla",
      "Toilet Umum",
      "Area Parkir",
      "Bak Penampungan Sampah"
    ],
    "latitude": -3.7895375,
    "longitude": 119.648046875,
    "fotoUtama": "assets/pasar/pasar_sentral_pinrang.jpg",
    "galeri": [
      "assets/pasar/pasar_sentral_pinrang.jpg"
    ],
    "deskripsi": "Pasar Sentral Pinrang merupakan pusat induk perdagangan dan distribusi bahan pokok dan barang penting (Bapokting) terbesar di Kabupaten Pinrang dengan aktivitas operasional setiap hari.",
    "sejarahSingkat": "Pusat aktivitas perdagangan tradisional tertua di kawasan perkotaan Pinrang yang terus direvitalisasi dan menjadi barometer stabilitas harga pangan daerah.",
    "sumber": [
      {
        "judul": "Laporan Pemantauan Harga Bapokting Harian 2026",
        "instansi": "Disperindag ESDM Kabupaten Pinrang",
        "tahun": 2026
      },
      {
        "judul": "Kecamatan Watang Sawitto Dalam Angka 2025",
        "instansi": "BPS Kabupaten Pinrang",
        "tahun": 2025
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Aktivitas perdagangan berlangsung harian dengan pemantauan enumerator setiap pagi.",
    "published": true,
    "showAsActive": true,
    "namaGoogleMaps": "Pasar Sentral Pinrang",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Pemda",
    "statusKewenangan": "Terkonfirmasi operasional Pemda 2026",
    "plusCode": "6J6X+56M",
    "statusKoordinat": "Titik tengah sel Plus Code — perlu validasi GPS pintu masuk",
    "jadwalGoogleMaps": "Setiap hari 05:00–18:00",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJz46KNQBNlC0Rb4Gkf7Vfvc8",
    "dasarReferensiMaster": "Perda 1/2024 + bukti operasional UPTD II 2026",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  },
  {
    "id": "pasar-pekkabata",
    "nama": "Pasar Pekkabata",
    "namaAlternatif": "Pasar Rakyat Pekkabata",
    "slug": "pasar-pekkabata",
    "kecamatan": "Duampanua",
    "desaKelurahan": "Pekkabata / Lampa",
    "alamat": "Listing utama: Lampa, Kec. Duampanua, Kabupaten Pinrang, Sulawesi Selatan 91253; listing kedua: 8G5X+H9H, Pekkabata, Kec. Duampanua, Kabupaten Pinrang, Sulawesi Selatan 91253, Indonesia",
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "Tinggi",
    "buktiOperasionalTerakhir": "Aktivitas hari pasar rutin Rabu & Sabtu dan dokumentasi pemantauan 2025–2026.",
    "klasifikasiHistoris": "Tipe B",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "Perlu Konfirmasi Internal",
    "hariPasar": [
      "Senin",
      "Rabu",
      "Jumat"
    ],
    "jamOperasional": "06.00 – 13.00 WITA",
    "luasLahanM2": null,
    "jumlahKios": 240,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [
      "Hasil Bumi",
      "Sayuran & Bumbu",
      "Ternak Unggas",
      "Ikan Laut & Tambak",
      "Bahan Pokok"
    ],
    "fasilitas": [
      "Los Pedagang",
      "Toilet Umum",
      "Area Parkir"
    ],
    "latitude": -3.6910625,
    "longitude": 119.548484375,
    "fotoUtama": "assets/pasar/pasar_pekkabata.jpg",
    "galeri": [
      "assets/pasar/pasar_pekkabata.jpg"
    ],
    "deskripsi": "Pasar Pekkabata merupakan pasar rakyat strategis di jalur poros Trans-Sulawesi bagian utara Kabupaten Pinrang yang menjadi pusat transaksi hasil pertanian dan perikanan masyarakat Duampanua.",
    "sejarahSingkat": "Pasar tradisional mingguan yang melayani kebutuhan masyarakat kecamatan Duampanua dan sekitarnya.",
    "sumber": [
      {
        "judul": "Kecamatan Duampanua Dalam Angka 2025",
        "instansi": "BPS Kabupaten Pinrang",
        "tahun": 2025
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Beroperasi aktif pada hari pasar resmi (Rabu dan Sabtu).",
    "published": true,
    "showAsActive": true,
    "namaGoogleMaps": "Pasar Pekkabata",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Pemda",
    "statusKewenangan": "Terkonfirmasi langsung 2026",
    "plusCode": "8G5X+H9H",
    "statusKoordinat": "Perlu perhatian — dua listing Google",
    "jadwalGoogleMaps": "Senin/Rabu/Jumat 05:00–11:00",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJbX8bXz9alC0RGCJMmMYuY1g",
    "dasarReferensiMaster": "Perda 1/2024 + bukti UPTD I 28/08/2026",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  },
  {
    "id": "pasar-bungi",
    "nama": "Pasar Bungi",
    "namaAlternatif": "Pasar Rakyat Bungi",
    "slug": "pasar-bungi",
    "kecamatan": "Duampanua",
    "desaKelurahan": "Bungi",
    "alamat": "CGQP+6CJ, Bungi, Kec. Duampanua, Kabupaten Pinrang, Sulawesi Selatan 91254, Indonesia",
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "Tinggi",
    "buktiOperasionalTerakhir": "Aktivitas transaksi pedagang dan dokumentasi survei lapangan 2025.",
    "klasifikasiHistoris": "Tipe C",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "Perlu Konfirmasi Internal",
    "hariPasar": [
      "Kamis",
      "Minggu"
    ],
    "jamOperasional": "06.00 – 12.00 WITA",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [
      "Pangan Pokok",
      "Hasil Kebun",
      "Ikan Segar"
    ],
    "fasilitas": [
      "Los Pasar",
      "Area Parkir"
    ],
    "latitude": -3.5619125,
    "longitude": 119.536015625,
    "fotoUtama": "assets/pasar/pasar_bungi.jpg",
    "galeri": [
      "assets/pasar/pasar_bungi.jpg"
    ],
    "deskripsi": "Pasar Bungi melayani kebutuhan masyarakat desa di wilayah Duampanua timur dengan komoditas utama produk pertanian lokal dan bahan pokok.",
    "sejarahSingkat": "Pasar desa tradisional yang menghubungkan produsen pertanian lokal dengan konsumen pedesaan.",
    "sumber": [
      {
        "judul": "Data Profil Sarana Perdagangan Kecamatan Duampanua",
        "instansi": "BPS Kabupaten Pinrang",
        "tahun": 2025
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Hari pasar aktif: Kamis dan Minggu.",
    "published": true,
    "showAsActive": true,
    "namaGoogleMaps": "Pasar Bungi",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Pemda",
    "statusKewenangan": "Master kerja — perlu sinkron register retribusi/aset",
    "plusCode": "CGQP+6CJ",
    "statusKoordinat": "Titik tengah sel Plus Code — perlu validasi GPS pintu masuk",
    "jadwalGoogleMaps": "Kamis/Minggu 05:00–12:00",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJFcZknr9dlC0R8u0zkc5Fcdc",
    "dasarReferensiMaster": "Perda 1/2024 (kerangka Pemda)",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  },
  {
    "id": "pasar-langnga",
    "nama": "Pasar Rakyat Langnga",
    "namaAlternatif": "Pasar Langnga",
    "slug": "pasar-langnga",
    "kecamatan": "Mattiro Sompe",
    "desaKelurahan": "Langnga",
    "alamat": "5G5C+X5R, Langnga, Kec. Mattiro Sompe, Kabupaten Pinrang, Sulawesi Selatan 91261, Indonesia",
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "Tinggi",
    "buktiOperasionalTerakhir": "Dokumentasi transaksi perikanan dan hasil bumi masyarakat pesisir 2025.",
    "klasifikasiHistoris": "Tipe B",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "Perlu Konfirmasi Internal",
    "hariPasar": [
      "Rabu",
      "Sabtu"
    ],
    "jamOperasional": "06.00 – 12.30 WITA",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [
      "Ikan Bandeng & Hasil Tambak",
      "Beras",
      "Sayuran",
      "Sembako"
    ],
    "fasilitas": [
      "Los Ikan",
      "Los Kering",
      "Area Parkir"
    ],
    "latitude": -3.8400125,
    "longitude": 119.520390625,
    "fotoUtama": "assets/pasar/pasar_langnga.jpg",
    "galeri": [
      "assets/pasar/pasar_langnga.jpg"
    ],
    "deskripsi": "Pasar Langnga adalah pusat perdagangan hasil tambak, perikanan laut, dan kebutuhan pokok bagi masyarakat di wilayah pesisir Kecamatan Mattiro Sompe.",
    "sejarahSingkat": "Pasar pesisir yang tumbuh seiring berkembangnya budidaya tambak bandeng dan udang di pesisir barat Pinrang.",
    "sumber": [
      {
        "judul": "Kecamatan Mattiro Sompe Dalam Angka 2025",
        "instansi": "BPS Kabupaten Pinrang",
        "tahun": 2025
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Pasar aktif melayani distribusi hasil laut dan kebutuhan harian.",
    "published": true,
    "showAsActive": true,
    "namaGoogleMaps": "Pasar Rakyat Langnga",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Pemda",
    "statusKewenangan": "Master kerja — perlu sinkron register retribusi/aset",
    "plusCode": "5G5C+X5R",
    "statusKoordinat": "Titik tengah sel Plus Code — perlu validasi GPS pintu masuk",
    "jadwalGoogleMaps": "Rabu/Sabtu 06:00–13:00",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJs1j67KSslS0RM78dPJiNjPA",
    "dasarReferensiMaster": "Perda 1/2024 (kerangka Pemda)",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  },
  {
    "id": "pasar-teppo-benteng",
    "nama": "Pasar Teppo",
    "namaAlternatif": "Pasar Teppo/Benteng",
    "slug": "pasar-teppo-benteng",
    "kecamatan": "Patampanua",
    "desaKelurahan": "Teppo / Benteng",
    "alamat": "7MW9+2FF, Teppo, Kec. Patampanua, Kabupaten Pinrang, Sulawesi Selatan 91252, Indonesia",
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "Tinggi",
    "buktiOperasionalTerakhir": "Survei perdagangan komoditas pertanian dan pedagang pasar 2025.",
    "klasifikasiHistoris": "Tipe B",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "Perlu Konfirmasi Internal",
    "hariPasar": [
      "Kamis",
      "Minggu"
    ],
    "jamOperasional": "06.00 – 12.00 WITA",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [
      "Padi & Beras",
      "Jagung",
      "Palawija",
      "Kebutuhan Pokok"
    ],
    "fasilitas": [
      "Los Pasar",
      "Area Parkir"
    ],
    "latitude": -3.7049375,
    "longitude": 119.668671875,
    "fotoUtama": "assets/pasar/pasar_teppo_benteng.jpg",
    "galeri": [
      "assets/pasar/pasar_teppo_benteng.jpg"
    ],
    "deskripsi": "Pasar Teppo/Benteng menjadi titik kumpul hasil pertanian dari lumbung pangan Patampanua dan sekitarnya.",
    "sejarahSingkat": "Pasar tradisional yang melayani sentra persawahan irigasi teknis di kawasan utara Saddang.",
    "sumber": [
      {
        "judul": "Kecamatan Patampanua Dalam Angka 2025",
        "instansi": "BPS Kabupaten Pinrang",
        "tahun": 2025
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Status operasional aktif diverifikasi melalui catatan statistik daerah.",
    "published": true,
    "showAsActive": true,
    "namaGoogleMaps": "Pasar Teppo/ Benteng",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Pemda",
    "statusKewenangan": "Master kerja — perlu sinkron register retribusi/aset",
    "plusCode": "7MW9+2FF",
    "statusKoordinat": "Titik tengah sel Plus Code — perlu validasi GPS pintu masuk",
    "jadwalGoogleMaps": "Kamis/Minggu ±05:05–12:12",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJpzFnIhdPlC0RPwt_uvQVGrQ",
    "dasarReferensiMaster": "Perda 1/2024 (kerangka Pemda)",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  },
  {
    "id": "pasar-kariango",
    "nama": "Pasar Kariango",
    "namaAlternatif": "Pasar Rakyat Kariango",
    "slug": "pasar-kariango",
    "kecamatan": "Mattiro Bulu",
    "desaKelurahan": "Pananrang / Dusun Kariango",
    "alamat": "4J8J+4WC, Pananrang, Kec. Mattiro Bulu, Kabupaten Pinrang, Sulawesi Selatan 91271, Indonesia",
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "Sedang",
    "buktiOperasionalTerakhir": "Dokumentasi riset pedagang pasar lokal 2025.",
    "klasifikasiHistoris": "Tipe C",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "UPTD Pasar Wilayah II",
    "statusVerifikasiUnitPengelola": "Perlu Konfirmasi Internal",
    "hariPasar": [
      "Selasa",
      "Jumat"
    ],
    "jamOperasional": "06.30 – 12.00 WITA",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [
      "Hasil Kebun",
      "Bapokting",
      "Sayur Mayur"
    ],
    "fasilitas": [
      "Los Pasar"
    ],
    "latitude": -3.8846875,
    "longitude": 119.632265625,
    "fotoUtama": "assets/pasar/pasar_kariango.jpg",
    "galeri": [
      "assets/pasar/pasar_kariango.jpg"
    ],
    "deskripsi": "Pasar Kariango merupakan pasar rakyat perdesaan yang melayani kebutuhan warga di Kecamatan Mattiro Bulu.",
    "sejarahSingkat": "Pasar mingguan masyarakat tani di dataran subur Mattiro Bulu.",
    "sumber": [
      {
        "judul": "Kecamatan Mattiro Bulu Dalam Angka 2025",
        "instansi": "BPS Kabupaten Pinrang",
        "tahun": 2025
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Aktivitas berkala pada hari pasar tertentu.",
    "published": true,
    "showAsActive": true,
    "namaGoogleMaps": "Pasar Kariango",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Pemda",
    "statusKewenangan": "Master kerja — perlu sinkron register retribusi/aset",
    "plusCode": "4J8J+4WC",
    "statusKoordinat": "Titik tengah sel Plus Code — perlu validasi GPS pintu masuk",
    "jadwalGoogleMaps": "Selasa/Jumat 06:00–12:00",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJAesUrT6ylS0RnQLI_H2PbVo",
    "dasarReferensiMaster": "Perda 1/2024 (kerangka Pemda)",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  },
  {
    "id": "pasar-pajalele",
    "nama": "Pasar Pajalele",
    "namaAlternatif": "Pasar Rakyat Pajalele",
    "slug": "pasar-pajalele",
    "kecamatan": "Lembang",
    "desaKelurahan": "Binanga Karaeng / Pajalele",
    "alamat": "FFVP+H9V, Binanga Karaeng, Kec. Lembang, Kabupaten Pinrang, Sulawesi Selatan 91254, Indonesia",
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "Sedang",
    "buktiOperasionalTerakhir": "Studi pedagang komoditas perdesaan 2025 di wilayah Lembang.",
    "klasifikasiHistoris": "Tipe C",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "Non-Pemda / belum terverifikasi",
    "statusVerifikasiUnitPengelola": "Perlu Konfirmasi Internal",
    "hariPasar": [
      "setiap hari"
    ],
    "jamOperasional": "06.00 – 11.30 WITA",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [
      "Hasil Perkebunan",
      "Kopi",
      "Sayuran Pegunungan",
      "Sembako"
    ],
    "fasilitas": [
      "Los Sederhana"
    ],
    "latitude": -3.5060125,
    "longitude": 119.485921875,
    "fotoUtama": "assets/pasar/pasar_pajalele.jpg",
    "galeri": [
      "assets/pasar/pasar_pajalele.jpg"
    ],
    "deskripsi": "Pasar Pajalele menjadi sarana transaksi hasil pertanian dataran tinggi dan kebutuhan pokok masyarakat di bagian utara Kecamatan Lembang.",
    "sejarahSingkat": "Pasar tradisional perintis di lereng perbukitan Lembang.",
    "sumber": [
      {
        "judul": "Kecamatan Lembang Dalam Angka 2025",
        "instansi": "BPS Kabupaten Pinrang",
        "tahun": 2025
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Aktivitas perdagangan berfokus pada hasil bumi dan kebutuhan pokok mingguan.",
    "published": true,
    "showAsActive": true,
    "namaGoogleMaps": "Pasar Pajalele Lembang",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Rakyat Lainnya",
    "statusKewenangan": "Pasar rakyat; bukan master Pasar Pemda saat ini",
    "plusCode": "FFVP+H9V",
    "statusKoordinat": "Titik tengah sel Plus Code — perlu validasi GPS pintu masuk",
    "jadwalGoogleMaps": "Listing menunjukkan setiap hari 06:00–23:00",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJP8SKCh9hlC0R6pHmbHodVcc",
    "dasarReferensiMaster": "Perda 2/2017 (referensi historis nama)",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  },
  {
    "id": "pasar-marawi",
    "nama": "Pasar Marawi",
    "namaAlternatif": "Pasar Rakyat Marawi",
    "slug": "pasar-marawi",
    "kecamatan": "Tiroang",
    "desaKelurahan": "Marawi",
    "alamat": "Jl. Poros Pinrang–Rappang KM 9, Marawi, Kec. Tiroang, Kabupaten Pinrang",
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "Sedang",
    "buktiOperasionalTerakhir": "Tercatat dalam dokumen historis Perda 2/2017 & jadwal pemantauan bergilir.",
    "klasifikasiHistoris": "Tipe B",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "UPTD Pasar Wilayah II",
    "statusVerifikasiUnitPengelola": "Perlu Konfirmasi Internal",
    "hariPasar": [
      "Rabu",
      "Sabtu"
    ],
    "jamOperasional": "Data sedang diperbarui",
    "luasLahanM2": null,
    "jumlahKios": 180,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [
      "Hortikultura",
      "Cabai Lokal",
      "Sayuran",
      "Beras"
    ],
    "fasilitas": [
      "Los Pedagang"
    ],
    "latitude": -3.8166921,
    "longitude": 119.7233924,
    "fotoUtama": "assets/pasar/pasar_marawi_tiroang.jpg",
    "galeri": [
      "assets/pasar/pasar_marawi_tiroang.jpg"
    ],
    "deskripsi": "Pasar Marawi di Kecamatan Tiroang tercatat sebagai salah satu sarana perdagangan hasil hortikultura dan palawija yang saat ini dalam proses pemutakhiran data operasional.",
    "sejarahSingkat": "Pasar penampung hasil sayur-mayur dan pertanian dataran Tiroang.",
    "sumber": [
      {
        "judul": "Perda Nomor 2 Tahun 2017 tentang Retribusi Pelayanan Pasar",
        "instansi": "Pemerintah Kabupaten Pinrang",
        "tahun": 2017
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Status operasional dan data detail sarana sedang dalam proses verifikasi lapangan lanjutan.",
    "published": true,
    "showAsActive": false,
    "namaGoogleMaps": "Pasar Marawi",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Pemda",
    "statusKewenangan": "Master kerja — perlu sinkron register retribusi/aset",
    "plusCode": "6P8X5PMF+89",
    "statusKoordinat": "Titik listing Google Maps; berada di Desa Marawi — perlu konfirmasi GPS pintu masuk",
    "jadwalGoogleMaps": "Rabu / Sabtu 05:00–13:00",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJsVB3JjRLlC0RlMa66qXuxrE",
    "dasarReferensiMaster": "Perda 1/2024 (kerangka Pemda)",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "GOOGLE_MAPS_LISTING_AND_PLUS_CODE",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif",
    "coordinateConfidence": "tinggi-digital",
    "coordinateSources": [
      "Google Maps listing Pasar Marawi",
      "Plus Code 6P8X5PMF+89",
      "Overlay batas indikatif BIG"
    ]
  },
  {
    "id": "pasar-kampoeng-djaja",
    "nama": "Pasar Kampoeng Djaja",
    "namaAlternatif": "Pasar Kampung Jaya",
    "slug": "pasar-kampoeng-djaja",
    "kecamatan": "Watang Sawitto",
    "desaKelurahan": "Jaya",
    "alamat": "6M43+25W, Jaya, Kec. Watang Sawitto, Kabupaten Pinrang, Sulawesi Selatan 91213, Indonesia",
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "Rendah",
    "buktiOperasionalTerakhir": "Tercantum dalam Perda Nomor 2 Tahun 2017.",
    "klasifikasiHistoris": "Tipe B",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "UPTD Pasar Wilayah II",
    "statusVerifikasiUnitPengelola": "Belum Dikonfirmasi",
    "hariPasar": [
      "Setiap hari"
    ],
    "jamOperasional": "Data sedang diperbarui",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "latitude": -3.7948875,
    "longitude": 119.652953125,
    "fotoUtama": "assets/pasar/pasar_placeholder_verified.jpg",
    "galeri": [
      "assets/pasar/pasar_placeholder_verified.jpg"
    ],
    "deskripsi": "Sarana perdagangan yang tercantum dalam basis data administratif historis di wilayah perkotaan Pinrang. Data operasional aktual sedang menunggu hasil verifikasi dinas.",
    "sejarahSingkat": "Tercatat dalam regulasi retribusi pasar daerah tahun 2017.",
    "sumber": [
      {
        "judul": "Perda Nomor 2 Tahun 2017 tentang Retribusi Pelayanan Pasar",
        "instansi": "Pemerintah Kabupaten Pinrang",
        "tahun": 2017
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Data operasional, alamat presisi, dan jadwal sedang diperbarui.",
    "published": true,
    "showAsActive": false,
    "namaGoogleMaps": "Pasar Kampoeng Djaja",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Pemda",
    "statusKewenangan": "Master kerja — perlu sinkron register retribusi/aset",
    "plusCode": "6M43+25W",
    "statusKoordinat": "Titik tengah sel Plus Code — perlu validasi GPS pintu masuk",
    "jadwalGoogleMaps": "Setiap hari 14:00–19:00",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJ9aouA_1MlC0R5eMgTFulcbI",
    "dasarReferensiMaster": "Perda 1/2024 (kerangka Pemda)",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  },
  {
    "id": "pasar-cempa",
    "nama": "Pasar Cempa",
    "namaAlternatif": "Pasar Rakyat Cempa",
    "slug": "pasar-cempa",
    "kecamatan": "Cempa",
    "desaKelurahan": "Cempa",
    "alamat": "7H3P+CWV, Cempa, Kec. Cempa, Kabupaten Pinrang, Sulawesi Selatan 91262, Indonesia",
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "Sedang",
    "buktiOperasionalTerakhir": "Tercantum dalam dokumen pembagian sarana perdagangan daerah.",
    "klasifikasiHistoris": "Tipe C",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "Belum Dikonfirmasi",
    "hariPasar": [
      "Selasa",
      "Jumat"
    ],
    "jamOperasional": "Data sedang diperbarui",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "latitude": -3.7463875,
    "longitude": 119.587296875,
    "fotoUtama": "assets/pasar/pasar_placeholder_verified.jpg",
    "galeri": [
      "assets/pasar/pasar_placeholder_verified.jpg"
    ],
    "deskripsi": "Pasar rakyat di wilayah Kecamatan Cempa yang melayani masyarakat tani dan tambak di sekitarnya.",
    "sejarahSingkat": "Pasar tradisional kecamatan Cempa dalam lampiran regulasi daerah.",
    "sumber": [
      {
        "judul": "Perda Nomor 2 Tahun 2017 tentang Retribusi Pelayanan Pasar",
        "instansi": "Pemerintah Kabupaten Pinrang",
        "tahun": 2017
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Data operasional dan jadwal pasar dalam verifikasi lapangan.",
    "published": true,
    "showAsActive": false,
    "namaGoogleMaps": "Pasar Cempa",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Pemda",
    "statusKewenangan": "Master kerja — perlu sinkron register retribusi/aset",
    "plusCode": "7H3P+CWV",
    "statusKoordinat": "Titik tengah sel Plus Code — perlu validasi GPS pintu masuk",
    "jadwalGoogleMaps": "Selasa/Jumat 07:00–12:00",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJ0eDv6_FRlC0RYVi1XTsDBRw",
    "dasarReferensiMaster": "Perda 1/2024 (kerangka Pemda)",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  },
  {
    "id": "pasar-leppangang",
    "nama": "Pasar Leppangang",
    "namaAlternatif": "Pasar Rakyat Leppangang",
    "slug": "pasar-leppangang",
    "kecamatan": "Patampanua",
    "desaKelurahan": "Mattiro Ade",
    "alamat": "8M5G+8WW, Mattiro Ade, Kec. Patampanua, Kabupaten Pinrang, Sulawesi Selatan 91252, Indonesia",
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "Sedang",
    "buktiOperasionalTerakhir": "Tercatat dalam dokumen regulasi retribusi pasar daerah.",
    "klasifikasiHistoris": "Tipe C",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "Belum Dikonfirmasi",
    "hariPasar": [
      "Rabu",
      "Sabtu"
    ],
    "jamOperasional": "Data sedang diperbarui",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "latitude": -3.6916375,
    "longitude": 119.677328125,
    "fotoUtama": "assets/pasar/pasar_placeholder_verified.jpg",
    "galeri": [
      "assets/pasar/pasar_placeholder_verified.jpg"
    ],
    "deskripsi": "Pasar rakyat di wilayah Leppangang, Kecamatan Patampanua yang tercantum dalam basis data administratif pasar Kabupaten Pinrang.",
    "sejarahSingkat": "Sarana perdagangan perdesaan dalam pembinaan Disperindag ESDM.",
    "sumber": [
      {
        "judul": "Perda Nomor 2 Tahun 2017 tentang Retribusi Pelayanan Pasar",
        "instansi": "Pemerintah Kabupaten Pinrang",
        "tahun": 2017
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Status operasional dan jadwal pasar dalam proses pemutakhiran.",
    "published": true,
    "showAsActive": false,
    "namaGoogleMaps": "Pasar Leppangang",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Pemda",
    "statusKewenangan": "Master kerja — perlu sinkron register retribusi/aset",
    "plusCode": "8M5G+8WW",
    "statusKoordinat": "Titik tengah sel Plus Code — perlu validasi GPS pintu masuk",
    "jadwalGoogleMaps": "Rabu/Sabtu 06:00–11:30",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJB6y0rGpOlC0RBpUwQt0xtcY",
    "dasarReferensiMaster": "Perda 1/2024 (kerangka Pemda)",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  },
  {
    "id": "pasar-lanrisang-jampue",
    "nama": "Pasar Lanrisang",
    "namaAlternatif": "Pasar Jampue / Djampue",
    "slug": "pasar-lanrisang-jampue",
    "kecamatan": "Lanrisang",
    "desaKelurahan": "Lanrisang / Jampue",
    "alamat": "3GVW+4MX, Unnamed Road, Lanrisang, Kabupaten Pinrang, Sulawesi Selatan 91272, Indonesia",
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "Sedang",
    "buktiOperasionalTerakhir": "Tercatat dalam dokumen administratif Perda 2/2017.",
    "klasifikasiHistoris": "Tipe C",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "UPTD Pasar Wilayah II",
    "statusVerifikasiUnitPengelola": "Belum Dikonfirmasi",
    "hariPasar": [
      "Kamis",
      "Minggu"
    ],
    "jamOperasional": "Data sedang diperbarui",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "latitude": -3.9071375,
    "longitude": 119.546734375,
    "fotoUtama": "assets/pasar/pasar_placeholder_verified.jpg",
    "galeri": [
      "assets/pasar/pasar_placeholder_verified.jpg"
    ],
    "deskripsi": "Pasar rakyat yang melayani kawasan pesisir dan pertanian di Kecamatan Lanrisang.",
    "sejarahSingkat": "Sarana perdagangan tradisional masyarakat Lanrisang.",
    "sumber": [
      {
        "judul": "Perda Nomor 2 Tahun 2017 tentang Retribusi Pelayanan Pasar",
        "instansi": "Pemerintah Kabupaten Pinrang",
        "tahun": 2017
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Data operasional dan jadwal pasar sedang diperbarui.",
    "published": true,
    "showAsActive": false,
    "namaGoogleMaps": "Pasar Djampue Lanrisang",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Pemda",
    "statusKewenangan": "Master kerja — perlu sinkron register retribusi/aset",
    "plusCode": "3GVW+4MX",
    "statusKoordinat": "Titik tengah sel Plus Code — perlu validasi GPS pintu masuk",
    "jadwalGoogleMaps": "Kamis/Minggu 05:00–12:00",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJ42hV8NSvlS0R5Jt4mjxrKxk",
    "dasarReferensiMaster": "Perda 1/2024 (kerangka Pemda)",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  },
  {
    "id": "pasar-suppa",
    "nama": "Pasar Suppa",
    "namaAlternatif": "Pasar Rakyat Suppa",
    "slug": "pasar-suppa",
    "kecamatan": "Suppa",
    "desaKelurahan": "Watang Suppa",
    "alamat": "Watang Suppa, Kec. Suppa, Kabupaten Pinrang",
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "Perlu Verifikasi Khusus",
    "buktiOperasionalTerakhir": "Catatan laporan 2022 mengindikasikan minimnya aktivitas pedagang pasca-pembangunan fisik; status pemanfaatan 2026 sedang dikonfirmasi dinas.",
    "klasifikasiHistoris": "Tipe C",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "",
    "statusVerifikasiUnitPengelola": "Belum Dikonfirmasi",
    "hariPasar": [],
    "jamOperasional": "Data sedang diperbarui",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "latitude": -3.9639013,
    "longitude": 119.6046165,
    "fotoUtama": "assets/pasar/pasar_suppa_evaluasi.jpg",
    "galeri": [
      "assets/pasar/pasar_suppa_evaluasi.jpg"
    ],
    "deskripsi": "Pasar Suppa merupakan bangunan pasar rakyat di pesisir selatan Kabupaten Pinrang. Status pemanfaatan dan operasional pedagang saat ini dalam tahap evaluasi dan pemutakhiran data oleh Disperindag ESDM.",
    "sejarahSingkat": "Dibangun sebagai fasilitas perdagangan penunjang kawasan pesisir Suppa.",
    "sumber": [
      {
        "judul": "Dokumentasi Evaluasi Pemanfaatan Sarana Perdagangan Daerah",
        "instansi": "Disperindag ESDM Kabupaten Pinrang",
        "tahun": 2025
      }
    ],
    "tanggalVerifikasi": "28 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Status operasional tidak diaktifkan langsung sebelum ada konfirmasi data pemanfaatan lapangan terbaru yang valid.",
    "published": true,
    "showAsActive": false,
    "masterDataStatus": "SUPPLEMENTAL_PERLU_VERIFIKASI",
    "masterDataNote": "Tidak tercantum pada workbook Google Maps 31 Agustus 2026.",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif",
    "metodeKoordinat": "GOOGLE_MAPS_LISTING",
    "statusKoordinat": "Titik listing Google Maps; berada di Watang Suppa — perlu konfirmasi GPS pintu masuk",
    "coordinateConfidence": "menengah-digital",
    "coordinateSources": [
      "Google Maps search Pasar Rakyat Suppa",
      "Overlay batas indikatif BIG"
    ],
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Pasar+Rakyat+Suppa+Pinrang"
  },
  {
    "id": "pasar-malimpung",
    "nama": "Pasar Malimpung",
    "namaAlternatif": "Pasar Rakyat Malimpung",
    "slug": "pasar-malimpung",
    "kecamatan": "Patampanua",
    "desaKelurahan": "Malimpung",
    "alamat": "7P8M+875, Malimpung, Kec. Patampanua, Kabupaten Pinrang, Sulawesi Selatan 91252, Indonesia",
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "Sedang",
    "buktiOperasionalTerakhir": "Tercantum dalam Perda Kabupaten Pinrang Nomor 2 Tahun 2017.",
    "klasifikasiHistoris": "Tipe C",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "Non-Pemda / belum terverifikasi",
    "statusVerifikasiUnitPengelola": "Belum Dikonfirmasi",
    "hariPasar": [
      "Rabu",
      "Sabtu"
    ],
    "jamOperasional": "Data sedang diperbarui",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "latitude": -3.7342375,
    "longitude": 119.733234375,
    "fotoUtama": "assets/pasar/pasar_placeholder_verified.jpg",
    "galeri": [
      "assets/pasar/pasar_placeholder_verified.jpg"
    ],
    "deskripsi": "Pasar perdesaan di kawasan Malimpung, Kecamatan Patampanua yang masuk dalam inventaris sarana pasar daerah.",
    "sejarahSingkat": "Pasar lokal pendukung aktivitas petani dan pekebun Malimpung.",
    "sumber": [
      {
        "judul": "Perda Nomor 2 Tahun 2017 tentang Retribusi Pelayanan Pasar",
        "instansi": "Pemerintah Kabupaten Pinrang",
        "tahun": 2017
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Jadwal dan aktivitas pasar sedang diperbarui.",
    "published": true,
    "showAsActive": false,
    "namaGoogleMaps": "Pasar Malimpung",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Rakyat Lainnya",
    "statusKewenangan": "Pasar rakyat; bukan master Pasar Pemda saat ini",
    "plusCode": "7P8M+875",
    "statusKoordinat": "Titik tengah sel Plus Code — perlu validasi GPS pintu masuk",
    "jadwalGoogleMaps": "Rabu/Sabtu 06:00–12:00",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJtR-uSHJJlC0R3cfTZQTL_V4",
    "dasarReferensiMaster": "Perda 2/2017 (referensi historis nama)",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  },
  {
    "id": "pasar-labolong",
    "nama": "Pasar Labolong",
    "namaAlternatif": "Pasar Rakyat Labolong",
    "slug": "pasar-labolong",
    "kecamatan": "Mattiro Sompe",
    "desaKelurahan": "Mattongang-Tongang / Dusun Labolong",
    "alamat": "6H27+MCM, Unnamed Road, Mattongang Tongang, Kec. Mattiro Sompe, Kabupaten Pinrang, Sulawesi Selatan 91261, Indonesia",
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "Sedang",
    "buktiOperasionalTerakhir": "Tercantum dalam dokumen regulasi retribusi pasar daerah 2017.",
    "klasifikasiHistoris": "Tipe C",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "Non-Pemda / belum terverifikasi",
    "statusVerifikasiUnitPengelola": "Belum Dikonfirmasi",
    "hariPasar": [],
    "jamOperasional": "Data sedang diperbarui",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "latitude": -3.7982875,
    "longitude": 119.563546875,
    "fotoUtama": "assets/pasar/pasar_placeholder_verified.jpg",
    "galeri": [
      "assets/pasar/pasar_placeholder_verified.jpg"
    ],
    "deskripsi": "Sarana pasar rakyat di wilayah Mattiro Sompe yang tercantum dalam basis data administratif pasar.",
    "sejarahSingkat": "Pasar desa pendukung sektor kelautan dan perikanan lokal.",
    "sumber": [
      {
        "judul": "Perda Nomor 2 Tahun 2017 tentang Retribusi Pelayanan Pasar",
        "instansi": "Pemerintah Kabupaten Pinrang",
        "tahun": 2017
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Data operasional dan jadwal pasar dalam verifikasi lapangan.",
    "published": true,
    "showAsActive": false,
    "namaGoogleMaps": "Pasar Labolong",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Rakyat Lainnya",
    "statusKewenangan": "Pasar rakyat; bukan master Pasar Pemda saat ini",
    "plusCode": "6H27+MCM",
    "statusKoordinat": "Titik tengah sel Plus Code — perlu validasi GPS pintu masuk",
    "jadwalGoogleMaps": null,
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJHf7BFCNTlC0R1H7CFt6wn-c",
    "dasarReferensiMaster": "Perda 2/2017 (referensi historis nama)",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  },
  {
    "id": "pasar-tuppu",
    "nama": "Pasar Tuppu",
    "namaAlternatif": "Pasar Rakyat Tuppu",
    "slug": "pasar-tuppu",
    "kecamatan": "Lembang",
    "desaKelurahan": "Tadokkong / Tuppu",
    "alamat": "FG4H+2VH, Taddokong, Kec. Lembang, Kabupaten Pinrang, Sulawesi Selatan 91254, Indonesia",
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "Sedang",
    "buktiOperasionalTerakhir": "Tercantum dalam inventaris regulasi retribusi pasar daerah.",
    "klasifikasiHistoris": "Tipe C",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017",
    "unitPengelola": "Non-Pemda / belum terverifikasi",
    "statusVerifikasiUnitPengelola": "Belum Dikonfirmasi",
    "hariPasar": [
      "Selasa",
      "Jumat"
    ],
    "jamOperasional": "Data sedang diperbarui",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "latitude": -3.5449458,
    "longitude": 119.5297239,
    "fotoUtama": "assets/pasar/pasar_placeholder_verified.jpg",
    "galeri": [
      "assets/pasar/pasar_placeholder_verified.jpg"
    ],
    "deskripsi": "Pasar rakyat di wilayah perbatasan Lembang yang tercantum dalam basis data sarana perdagangan daerah.",
    "sejarahSingkat": "Pasar tradisional di jalur penghubung pegunungan utara Pinrang.",
    "sumber": [
      {
        "judul": "Perda Nomor 2 Tahun 2017 tentang Retribusi Pelayanan Pasar",
        "instansi": "Pemerintah Kabupaten Pinrang",
        "tahun": 2017
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Data operasional dan jadwal pasar dalam pemutakhiran berkala.",
    "published": true,
    "showAsActive": false,
    "namaGoogleMaps": "Pasar Tradisional Tuppu",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Rakyat Lainnya",
    "statusKewenangan": "Pasar rakyat; bukan master Pasar Pemda saat ini",
    "plusCode": "FG4H+2VH",
    "statusKoordinat": "Terverifikasi silang digital; berada di Desa Tadokkong — konfirmasi GPS pintu masuk tetap disarankan",
    "jadwalGoogleMaps": "Selasa/Jumat 05:00–11:00",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJI9--SfRdlC0RG7ufewALyfQ",
    "dasarReferensiMaster": "Perda 2/2017 (referensi historis nama)",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "GOOGLE_MAPS_AND_DOCUMENT_CROSSCHECK",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif",
    "coordinateConfidence": "tinggi-digital",
    "coordinateSources": [
      "Google Maps listing Pasar Tradisional Tuppu",
      "Dokumen pemetaan TPS Pinrang",
      "Overlay batas indikatif BIG"
    ]
  },
  {
    "id": "pasar-paleteang",
    "nama": "Pasar Paleteang",
    "namaAlternatif": "Kandidat kecocokan — belum terbukti objek yang sama",
    "slug": "pasar-paleteang",
    "kecamatan": "Paleteang",
    "desaKelurahan": "Temmassarangnge",
    "alamat": "6MC2+J9H Temmassarangnge, Kabupaten Pinrang, Sulawesi Selatan",
    "statusOperasional": "tidak-aktif",
    "statusLabel": "Tidak Aktif",
    "tingkatKeyakinanStatus": "Tinggi",
    "buktiOperasionalTerakhir": "Data lapangan dan statistik menunjukkan lokasi ini sudah tidak beroperasi sebagai pasar aktif.",
    "klasifikasiHistoris": "Tipe A (Berdasarkan Regulasi Historis Perda 2/2017)",
    "dasarKlasifikasi": "Perda Kabupaten Pinrang Nomor 2 Tahun 2017 (Klasifikasi Historis)",
    "unitPengelola": "Non-Pemda / belum terverifikasi",
    "statusVerifikasiUnitPengelola": "Aset / Non-Operasional",
    "hariPasar": [
      "Selasa",
      "Kamis",
      "Minggu malam"
    ],
    "jamOperasional": "Tidak Beroperasi",
    "luasLahanM2": null,
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "latitude": -3.77842302192501,
    "longitude": 119.651104130629,
    "fotoUtama": "assets/pasar/pasar_paleteang_inpres.jpg",
    "galeri": [
      "assets/pasar/pasar_paleteang_inpres.jpg"
    ],
    "deskripsi": "Pasar Paleteang merupakan pasar lama di Kecamatan Paleteang yang saat ini tidak beroperasi sebagai pasar aktif. Nama 'Kompleks Pasar Paleteang' masih dikenal luas oleh masyarakat setempat sebagai penunjuk kawasan.",
    "sejarahSingkat": "Pasar Paleteang tercantum dalam regulasi lama sebagai Pasar Tipe A berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017. Namun berdasarkan perkembangan kondisi lapangan dan data statistik, pasar tersebut sudah tidak beroperasi sebagai sarana transaksi aktif.",
    "sumber": [
      {
        "judul": "Kecamatan Paleteang Dalam Angka 2025",
        "instansi": "BPS Kabupaten Pinrang",
        "tahun": 2025
      },
      {
        "judul": "Perda Nomor 2 Tahun 2017 tentang Retribusi Pelayanan Pasar",
        "instansi": "Pemerintah Kabupaten Pinrang",
        "tahun": 2017
      }
    ],
    "tanggalVerifikasi": "31 Agustus 2026",
    "tahunData": "2026",
    "catatanVerifikasi": "Nama Pasar Paleteang masih ditemukan pada dokumen/regulasi lama. Status operasional saat ini berbeda dengan status administratif historis.",
    "published": true,
    "showAsActive": false,
    "namaGoogleMaps": "Pasar Paleteang",
    "jenisPasar": "Pasar Rakyat",
    "kategoriPengelolaan": "Pasar Rakyat Lainnya",
    "statusKewenangan": "Pasar rakyat; bukan master Pasar Pemda saat ini",
    "plusCode": "6MC2+J9H",
    "statusKoordinat": "Kandidat — jangan dianggap final",
    "jadwalGoogleMaps": "Selasa/Kamis/Minggu malam",
    "googleMapsUrl": "https://www.google.com/maps/place/?q=place_id:ChIJaRDUW-5NlC0Ra9CiLqACrbg",
    "dasarReferensiMaster": "Perda 2/2017 + kandidat Google Maps",
    "masterDataStatus": "TERVERIFIKASI_WORKBOOK_GOOGLE_MAPS",
    "masterDataSource": "Master_Data_Pasar_Pinrang_Google_Maps_2026-08-31.xlsx",
    "metodeKoordinat": "PLUS_CODE_CELL_CENTER",
    "dataVersion": "2026-08-31-market-single-source-v3",
    "boundaryReference": "BIG/Batas Administrasi — batas desa/kelurahan bersifat indikatif"
  }
];

if (typeof window !== "undefined") window.PINRANG_ALL_MARKETS = PINRANG_ALL_MARKETS;
