(function(){'use strict';
const state={prices:[],agents:[],bases:[],fuel:[],markets:[],products:[],news:[],skm:null,settings:null,config:[],slides:[],index:0,paused:false,timer:null,refreshTimer:null,startedAt:0};
const $=id=>document.getElementById(id), clean=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number.isFinite(Number(v))&&Number(v)>0?'Rp '+Math.round(Number(v)).toLocaleString('id-ID'):'Belum tersedia';
const dateValue=v=>{if(!v)return 0;if(typeof v.toDate==='function')return v.toDate().getTime();const d=new Date(v);return Number.isFinite(d.getTime())?d.getTime():0};
const defaultConfig=[['welcome',1,10],['announcement',2,12],['hours',3,12],['services',4,16],['maklumat',5,18],['skm',6,12],['prices',7,24],['lpg',8,20],['fuel',9,15],['markets',10,22],['ikm',11,17],['news',12,18],['complaint',13,15],['closing',14,10]].map(([id,order,duration])=>({id,enabled:id!=='announcement',order,duration}));
function card(icon,value,label,extra=''){return `<article class="tv-card"><em>${icon}</em><b>${value}</b><small>${clean(label)}${extra?`<br>${extra}`:''}</small></article>`}
function slide(id,html){return {id,html};}
function buildSlides(){const configured=new Map(state.config.map(x=>[x.id,x])),source=defaultConfig.map(base=>({...base,...(configured.get(base.id)||{})}));const active=source.filter(x=>x.enabled!==false&&(!x.startDate||dateValue(x.startDate)<=Date.now())&&(!x.endDate||dateValue(x.endDate)>=Date.now())).sort((a,b)=>{const rank=x=>x.id==='welcome'?-1000:x.priority?-500:Number(x.order)||999;return rank(a)-rank(b)});const builders={
welcome:()=>slide('welcome',`<div class="eyebrow">Informasi • Pelayanan • Transparansi</div><h1>Selamat Datang di Layanan Publik</h1><p>Dinas Perindustrian, Perdagangan, Energi dan Sumber Daya Mineral Kabupaten Pinrang.</p>`),
announcement:()=>{const item=active.find(x=>x.id==='announcement'),title=String(item?.title||'').trim(),message=String(item?.message||'').trim();return item?.enabled!==false&&(title||message)?slide('announcement',`<div class="eyebrow">Pengumuman Layanan</div><h2>${clean(title)}</h2><p>${clean(message)}</p>`):null;},
hours:()=>slide('hours',`<div class="eyebrow">Jam & Lokasi Pelayanan</div><div class="tv-split"><div><h2>Kami Siap Melayani Anda</h2><div class="tv-list"><div><i></i>Senin–Kamis • 08.00–16.00 WITA</div><div><i></i>Jumat • 08.00–16.30 WITA</div><div><i></i>Jalan Bintang No. 1, Kabupaten Pinrang</div></div></div><div class="tv-stat">MANTAP</div></div>`),
services:()=>slide('services',`<div class="eyebrow">Layanan Kami</div><h2>Pelayanan Publik Disperindag ESDM</h2><div class="tv-grid">${card('⚖️','Tera','Tera dan tera ulang UTTP')}${card('🏭','Industri','OSS, SIINas dan TKDN')}${card('🏪','Perdagangan','Pasar dan distribusi')}${card('🔥','Energi','LPG dan penyalur BBM')}${card('📣','Pengaduan','Kanal aspirasi publik')}${card('📄','PPID','Informasi publik')}</div>`),
maklumat:()=>slide('maklumat',`<div class="tv-maklumat"><div class="tv-maklumat-seal"><img src="assets/brand/logo_pinrang_opt.png" alt="Logo Kabupaten Pinrang"><span>Maklumat Pelayanan Publik</span></div><blockquote>“Dengan ini, kami seluruh jajaran pimpinan dan aparatur Dinas Perindustrian, Perdagangan, Energi dan Sumber Daya Mineral Kabupaten Pinrang menyatakan sanggup menyelenggarakan pelayanan sesuai standar pelayanan yang telah ditetapkan dan apabila tidak menepati janji ini, kami siap menerima sanksi sesuai peraturan perundang-undangan yang berlaku.”</blockquote><div class="tv-maklumat-footer"><div><small>Motto Pelayanan</small><strong>MANTAP</strong></div><p>Melayani Anda dengan <b>Transparan</b>, <b>Adil</b> & <b>Profesional</b></p></div></div>`),
skm:()=>{const s=state.skm||{};return slide('skm',`<div class="eyebrow">Kepuasan Masyarakat</div><div class="tv-split"><div><h2>Indeks Kepuasan Masyarakat</h2><p>Penilaian masyarakat membantu kami meningkatkan kualitas pelayanan.</p></div><div><div class="tv-stat">${clean(s.score||s.nilai||'88,64')}</div><p><b>${clean(s.grade||s.mutu||'Sangat Baik')}</b> • ${clean(s.respondents||s.responden||450)} responden</p></div></div>`);},
prices:()=>{const rows=state.prices.slice().sort((a,b)=>Number(a.variantId||999)-Number(b.variantId||999));return slide('prices',`<div class="eyebrow">Harga Bahan Pokok Kabupaten Pinrang</div><div class="tv-price-grid">${rows.length?rows.map(x=>{const current=Number(x.displayPrice),prev=Number(x.comparisonPrice),d=Number.isFinite(Number(x.delta))?Number(x.delta):current-prev,status=String(x.changeStatus||''),t=/naik/i.test(status)||d>0?'↑ Naik':/turun/i.test(status)||d<0?'↓ Turun':'→ Tetap',cl=t.includes('Naik')?'trend-up':t.includes('Turun')?'trend-down':'trend-stable';return `<article class="tv-price-item"><span>${clean(x.commodityName||'Komoditas')}</span><b>${money(current)}</b><small>per ${clean(x.unit||'kg')} • <i class="${cl}">${t}</i></small></article>`}).join(''):'<p>Data SP2KP belum tersedia dari cloud.</p>'}</div><p class="tv-source">Seluruh ${rows.length} komoditas • Sumber: SP2KP Kementerian Perdagangan RI • Data ${clean(rows[0]?.dataDate||'')}</p>`);},
lpg:()=>{const agents=state.agents.slice().sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''),'id'));return slide('lpg',`<div class="eyebrow">Agen & Pangkalan LPG 3 Kg Kabupaten Pinrang</div><div class="tv-lpg-summary"><b>${agents.length||'—'} Agen Resmi</b><span>${state.bases.length||'—'} pangkalan terdata • ${new Set(state.bases.map(x=>x.kecamatan).filter(Boolean)).size||'—'} kecamatan</span></div><div class="tv-agent-grid">${agents.length?agents.map((x,i)=>`<article><em>${String(i+1).padStart(2,'0')}</em><div><b>${clean(x.name||'Agen LPG')}</b><small>${clean(x.address||'Kabupaten Pinrang')}</small></div></article>`).join(''):'<p>Data agen LPG belum tersedia dari Firestore.</p>'}</div><p class="tv-source">Beli LPG 3 kg di pangkalan resmi yang terhubung dengan agen resmi.</p>`);},
fuel:()=>{const c={spbu_reguler:0,spbu_kompak:0,spbun:0,pertashop:0};state.fuel.forEach(x=>{const k=String(x.kategori_code||'').toLowerCase();if(k in c)c[k]++;});return slide('fuel',`<div class="eyebrow">Penyalur BBM Resmi</div><h2>${state.fuel.length||'—'} Titik Penyalur Kabupaten Pinrang</h2><div class="tv-grid">${card('⛽',c.spbu_reguler,'SPBU Reguler')}${card('🛢️',c.spbu_kompak,'SPBU Compact / APMS')}${card('🏪',c.pertashop,'Pertashop')}${card('⚓',c.spbun,'SPBUN Nelayan')}</div>`);},
markets:()=>{const rows=state.markets.filter(m=>m.published!==false).sort((a,b)=>String(a.nama).localeCompare(String(b.nama),'id'));return slide('markets',`<div class="eyebrow">Direktori Pasar Kabupaten Pinrang</div><div class="tv-market-head"><h2>${rows.length} Pasar & Sarana Perdagangan</h2><span>Nama pasar • kecamatan • hari operasional</span></div><div class="tv-market-grid">${rows.length?rows.map(x=>{const days=Array.isArray(x.hariPasar)?x.hariPasar.join(', '):x.hariPasar||x.jadwalGoogleMaps||x.jamOperasional||'Jadwal diperbarui';return `<article><span class="market-status ${x.showAsActive===true?'active':'review'}">${x.showAsActive===true?'Aktif':'Verifikasi'}</span><b>${clean(x.nama)}</b><small>Kec. ${clean(x.kecamatan||'-')} • ${clean(days)}</small></article>`}).join(''):'<p>Data pasar belum tersedia dari Firestore.</p>'}</div>`);},
ikm:()=>{const p=state.products.filter(x=>x.published!==false).slice(0,4);return slide('ikm',`<div class="eyebrow">Produk Unggulan Bumi Lasinrang</div><h2>Karya IKM Kabupaten Pinrang</h2><div class="tv-grid">${p.length?p.map(x=>`<article class="tv-card tv-product-card"><img src="${clean(x.img||x.image)}" alt="${clean(x.name)}"><div><b>${clean(x.name)}</b><small>${clean(x.category_label||x.category||'Produk IKM')} • ${clean(x.location||'Kabupaten Pinrang')}</small></div></article>`).join(''):'<p>Data produk IKM belum tersedia dari Firestore.</p>'}</div>`);},
news:()=>{const rows=state.news.slice(0,2);return rows.length?rows.map((n,i)=>slide(`news-${n.id}`,`<div class="tv-split"><div><div class="eyebrow">Berita Terbaru ${i+1} dari ${rows.length}</div><h2>${clean(n.title||n.judul)}</h2><p>${clean(n.excerpt||n.ringkasan||'Rilis kegiatan dan pelayanan terbaru.')}</p><span class="tv-date-badge">${clean(n.date||n.publishedDate||n.published_at||'Publikasi terbaru')}</span></div><div class="tv-photo"><img src="${clean(n.featuredImage||n.image||n.img||n.imageUrl||'assets/brand/cover_arsip_berita.png')}" alt="Foto berita"></div></div>`)):slide('news-empty','<h2>Berita terbaru belum tersedia dari Firestore.</h2>');},
complaint:()=>slide('complaint',`<div class="eyebrow">Pengaduan Publik</div><h2>Ada Keluhan terhadap Pelayanan Kami?</h2><div class="tv-grid">${card('📱','0823 1600 2226','WhatsApp layanan')}${card('📷','@perindagempinrang','Instagram resmi')}${card('🌐','Website','Form pengaduan online')}${card('🏛️','SP4N LAPOR!','Kanal pengaduan nasional')}</div><p class="tv-source">Identitas pelapor dilindungi sesuai ketentuan.</p>`),
closing:()=>slide('closing',`<div class="eyebrow">Terima Kasih</div><h1>Melayani dengan Transparan, Adil & Profesional</h1><p>MANTAP • Melayani Anda dengan Transparan, Adil dan Profesional.</p>`)};
state.slides=active.flatMap(c=>{const built=builders[c.id]?.();return (Array.isArray(built)?built:[built]).filter(Boolean).map(item=>({...item,duration:Math.max(6,Number(c.duration)||Number(state.settings?.defaultDuration)||12)}))});const previewId=new URLSearchParams(location.search).get('slide');const previewIndex=previewId?state.slides.findIndex(item=>item.id===previewId||item.id.startsWith(`${previewId}-`)):-1;if(previewIndex>=0){state.index=previewIndex;state.paused=true}else if(state.index>=state.slides.length)state.index=0;renderStage();}
function renderStage(){const stage=$('tvStage');stage.innerHTML=state.slides.map((s,i)=>`<article class="tv-slide${i===state.index?' active':''}" data-slide="${clean(s.id)}">${s.html}</article>`).join('');show(state.index);}
function show(index){if(!state.slides.length)return;state.index=(index+state.slides.length)%state.slides.length;document.querySelectorAll('.tv-slide').forEach((n,i)=>n.classList.toggle('active',i===state.index));clearTimeout(state.timer);const d=state.slides[state.index].duration*1000;state.startedAt=Date.now();const bar=$('tvProgress');bar.style.transition='none';bar.style.width='0';requestAnimationFrame(()=>requestAnimationFrame(()=>{bar.style.transition=`width ${d}ms linear`;bar.style.width=state.paused?'0':'100%'}));if(!state.paused)state.timer=setTimeout(()=>show(state.index+1),d);}
function bindCollection(name,apply,query){if(!db)return;let ref=db.collection(name);if(query)ref=query(ref);ref.onSnapshot({includeMetadataChanges:true},s=>{if(s.metadata.fromCache)return;const rows=s.docs.map(d=>({id:d.id,...d.data()}));apply(rows);buildSlides();$('tvStatus').textContent='Data resmi terhubung';},e=>{apply([]);buildSlides();$('tvStatus').textContent='Sebagian data resmi belum dapat dimuat';console.warn('[TV]',name,e.code||e.message)});}
function applyTvSettings(rows){state.settings=rows.find(x=>x.id==='settings')||null;state.config=rows.filter(x=>x.id!=='settings'&&x.type!=='settings');if(!state.settings)return;const items=Array.isArray(state.settings.tickerItems)?state.settings.tickerItems.map(x=>String(x).trim()).filter(Boolean):[];if(items.length){const doubled=[...items,...items];document.querySelector('.ticker-track').innerHTML=doubled.map(x=>`<span>${clean(x)}</span>`).join('')}document.querySelector('.ticker-track').style.animationDuration=`${Math.max(20,Number(state.settings.tickerSpeed)||42)}s`;state.paused=state.settings.autoplay===false;$('tvPause').textContent=state.paused?'▶':'Ⅱ';document.querySelector('.tv-controls').style.display=state.settings.showControls===false?'none':'flex';clearTimeout(state.refreshTimer);const minutes=Number(state.settings.refreshMinutes)||0;if(minutes>0)state.refreshTimer=setTimeout(()=>location.reload(),minutes*60000)}
function initData(){if(!db){$('tvStage').innerHTML='<div class="tv-loading"><b>Firestore belum tersedia. Tidak ada data lokal pengganti yang ditampilkan.</b></div>';return}bindCollection('market_prices_latest',x=>state.prices=x);bindCollection('lpg_agents',x=>state.agents=x);bindCollection('lpg_pangkalan',x=>state.bases=x);bindCollection('bbm_outlets',x=>state.fuel=x);bindCollection('markets',x=>state.markets=x);bindCollection('ikm_products',x=>state.products=x);bindCollection('news',x=>state.news=x.sort((a,b)=>dateValue(b.publishedAt||b.published_at||b.updatedAt||b.date)-dateValue(a.publishedAt||a.published_at||a.updatedAt||a.date)),ref=>ref.where('status','==','published'));bindCollection('skm',x=>state.skm=x[0]||null);bindCollection('tvSlides',applyTvSettings)}
function clock(){const now=new Date(),date=new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Makassar',weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(now),time=new Intl.DateTimeFormat('id-ID',{timeZone:'Asia/Makassar',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(now);$('tvDate').textContent=date;$('tvClock').textContent=time.replaceAll('.',':')+' WITA'}
document.addEventListener('DOMContentLoaded',()=>{clock();setInterval(clock,1000);$('tvPrev').onclick=()=>show(state.index-1);$('tvNext').onclick=()=>show(state.index+1);$('tvPause').onclick=()=>{state.paused=!state.paused;$('tvPause').textContent=state.paused?'▶':'Ⅱ';show(state.index)};$('tvFullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();initData()});
})();
