// src/mockdata/index.js
// Mock data untuk development frontend tanpa koneksi Firestore

export const MOCK_STATS = {
  totalMentions:    147,
  criticalIssues:   3,
  negativePct:      17,
  totalAspirations: 21,
  activeSources:    32,
  newDomains:       2,
};

export const MOCK_CRITICAL_ISSUES = [
  {
    id:            "lpg_bungi_20260825",
    title:         "Dugaan Pelanggaran Distribusi LPG 3 Kg di Bungi",
    category:      "lpg",
    status:        "tinggi",
    criticalScore: 87,
    sourceCount:   5,
    mentionCount:  8,
    sentiment:     "negative",
    escalationStatus: "regional",
    location:      { district: "Duampanua", village: "Bungi" },
    latestUpdate:  "2026-08-26T14:00:00+07:00",
    escalationTimeline: [
      { time: "08:15", source: "Voice Sulawesi", tier: "A" },
      { time: "09:10", source: "BeritaSulsel",   tier: "A+" },
      { time: "10:30", source: "detikSulsel",    tier: "A+" },
      { time: "13:00", source: "ANTARA",         tier: "A+" },
    ],
    watchlistMatch: ["lpg"],
  },
  {
    id:            "bbm_suppa_20260724",
    title:         "Distribusi Solar Subsidi APMS Suppa Dipertanyakan",
    category:      "bbm",
    status:        "waspada",
    criticalScore: 74,
    sourceCount:   4,
    mentionCount:  12,
    sentiment:     "negative",
    escalationStatus: "regional",
    location:      { district: "Suppa", village: "" },
    latestUpdate:  "2026-07-25T09:00:00+07:00",
    escalationTimeline: [
      { time: "07:30", source: "Pinrang Terkini", tier: "A+" },
      { time: "10:00", source: "BeritaSulsel",    tier: "A+" },
      { time: "14:20", source: "Voice Sulawesi",  tier: "A+" },
      { time: "16:00", source: "detikSulsel",     tier: "A+" },
    ],
    watchlistMatch: ["solar"],
  },
  {
    id:            "pangan_pinrang_20260828",
    title:         "Fluktuasi Harga Pangan di 3 Kecamatan",
    category:      "harga_pangan",
    status:        "monitor",
    criticalScore: 58,
    sourceCount:   3,
    mentionCount:  5,
    sentiment:     "negative",
    escalationStatus: "local",
    location:      { district: "Watang Sawitto", village: "" },
    latestUpdate:  "2026-08-28T07:00:00+07:00",
    escalationTimeline: [
      { time: "07:00", source: "Harian Fajar", tier: "A+" },
      { time: "08:30", source: "Parepos",      tier: "A+" },
      { time: "09:15", source: "Pinrang Terkini", tier: "A+" },
    ],
    watchlistMatch: [],
  },
];

export const MOCK_MENTIONS = [
  {
    id:           "m_001",
    title:        "Kontrak Pangkalan LPG di Pinrang Diputus Gegara Ogah Jual Tabung ke Tetangga",
    excerpt:      "Disperindag ESDM Kabupaten Pinrang memutus kontrak pangkalan LPG yang menolak menjual kepada warga setempat dan hanya melayani pembeli dari luar.",
    thumbnailUrl: "https://awsimages.detik.net.id/community/media/visual/2026/08/25/lpg-pinrang.jpg",
    sourceUrl:    "https://detik.com/sulsel/berita/d-8634122/kontrak-pangkalan-lpg-di-pinrang-diputus",
    sourceName:   "detikSulsel",
    sourceDomain: "detik.com",
    sourceTier:   "A+",
    sourceWeight: 0.95,
    publishedAt:  "2026-08-25T18:49:00+07:00",
    geo:          { district: "Duampanua", village: "Bungi" },
    topics:       ["LPG", "Distribusi BBM"],
    sentiment:    { label: "negative", score: -0.72, reason: "Keluhan warga atas distribusi LPG tidak sesuai HET" },
    aspiration:   { detected: true, type: "complaint" },
    relevanceScore: 96,
    criticalScore:  87,
    issueId:      "lpg_bungi_20260825",
  },
  {
    id:           "m_002",
    title:        "Atensi Aduan Masyarakat: Polres Pinrang Pastikan Distribusi Solar Subsidi di Suppa Sesuai Aturan",
    excerpt:      "Polres Pinrang merespons aduan warga terkait dugaan penyalahgunaan solar subsidi di APMS Suppa dengan melakukan pemeriksaan mendalam.",
    thumbnailUrl: "https://pinrang.terkini.id/wp-content/uploads/2026/07/solar-suppa.jpg",
    sourceUrl:    "https://pinrang.terkini.id/2026/07/09/atensi-aduan-masyarakat-polres-pinrang-pastikan-distribusi-solar-subsidi-di-suppa-sesuai-aturan",
    sourceName:   "Pinrang Terkini",
    sourceDomain: "pinrang.terkini.id",
    sourceTier:   "A+",
    sourceWeight: 0.85,
    publishedAt:  "2026-07-09T10:30:00+07:00",
    geo:          { district: "Suppa", village: "" },
    topics:       ["Distribusi BBM", "Solar Subsidi"],
    sentiment:    { label: "neutral", score: -0.20, reason: "Pemerintah merespons aduan, belum ada kesimpulan" },
    aspiration:   { detected: true, type: "complaint" },
    relevanceScore: 91,
    criticalScore:  74,
    issueId:      "bbm_suppa_20260724",
  },
  {
    id:           "m_003",
    title:        "Harga Cabai di Pasar Sentral Pinrang Melonjak 40% Jelang Akhir Bulan",
    excerpt:      "Harga cabai rawit merah di Pasar Sentral Pinrang mencapai Rp 85.000 per kilogram, melonjak hampir 40% dibanding pekan lalu.",
    thumbnailUrl: "",
    sourceUrl:    "https://harian.fajar.co.id/category/pinrang/harga-cabai-pinrang-melonjak",
    sourceName:   "Harian Fajar – Pinrang",
    sourceDomain: "harian.fajar.co.id",
    sourceTier:   "A+",
    sourceWeight: 0.90,
    publishedAt:  "2026-08-28T07:15:00+07:00",
    geo:          { district: "Watang Sawitto", village: "" },
    topics:       ["Harga Pangan", "Cabai"],
    sentiment:    { label: "negative", score: -0.65, reason: "Kenaikan harga signifikan berdampak pada daya beli warga" },
    aspiration:   { detected: false, type: "none" },
    relevanceScore: 88,
    criticalScore:  58,
    issueId:      "pangan_pinrang_20260828",
  },
  {
    id:           "m_004",
    title:        "Disperindag ESDM Pinrang Gelar Pasar Murah Ramadan, 500 Paket Sembako Tersedia",
    excerpt:      "Dalam rangka stabilisasi harga menjelang hari raya, Disperindag ESDM Kabupaten Pinrang menggelar pasar murah dengan menyediakan 500 paket sembako bersubsidi.",
    thumbnailUrl: "https://sbl.pinrangkab.go.id/uploads/pasar-murah.jpg",
    sourceUrl:    "https://sbl.pinrangkab.go.id/artikel/disperindag-esdm-gelar-pasar-murah",
    sourceName:   "SBL Radio Pinrang",
    sourceDomain: "sbl.pinrangkab.go.id",
    sourceTier:   "A+",
    sourceWeight: 0.90,
    publishedAt:  "2026-08-20T09:00:00+07:00",
    geo:          { district: "Watang Sawitto", village: "" },
    topics:       ["Pasar Murah", "Sembako", "Kegiatan Pemerintah"],
    sentiment:    { label: "positive", score: 0.82, reason: "Program nyata pemerintah untuk stabilisasi harga sembako" },
    aspiration:   { detected: false, type: "none" },
    relevanceScore: 95,
    criticalScore:  15,
    issueId:      "",
  },
  {
    id:           "m_005",
    title:        "Satreskrim Polres Pinrang Disorot Soal APMS Suppa, Diduga Ada Oknum yang Bekingi",
    excerpt:      "Beredar informasi bahwa oknum anggota kepolisian diduga terlibat dalam perlindungan praktek penyalahgunaan solar subsidi di APMS Suppa.",
    thumbnailUrl: "https://www.okita.news/img/polres-pinrang.jpg",
    sourceUrl:    "https://www.okita.news/2026/07/satreskrim-polres-pinrang-disorot.html",
    sourceName:   "Okita News",
    sourceDomain: "okita.news",
    sourceTier:   "A",
    sourceWeight: 0.78,
    publishedAt:  "2026-07-15T14:00:00+07:00",
    geo:          { district: "Suppa", village: "" },
    topics:       ["Distribusi BBM", "Hukum & Keamanan"],
    sentiment:    { label: "negative", score: -0.88, reason: "Dugaan keterlibatan oknum aparat dalam penyalahgunaan BBM subsidi" },
    aspiration:   { detected: true, type: "report" },
    relevanceScore: 85,
    criticalScore:  82,
    issueId:      "bbm_suppa_20260724",
  },
];

export const MOCK_SOURCE_HEALTH = [
  { id: "pinrang_terkini", name: "Pinrang Terkini",  tier: "A+", status: "healthy", minutesAgo: 8  },
  { id: "detik_sulsel",    name: "detikSulsel",      tier: "A+", status: "healthy", minutesAgo: 11 },
  { id: "antara_makassar", name: "ANTARA Makassar",  tier: "A+", status: "healthy", minutesAgo: 19 },
  { id: "rri_makassar",    name: "RRI Makassar",     tier: "A+", status: "healthy", minutesAgo: 6  },
  { id: "harian_fajar",    name: "Harian Fajar",     tier: "A+", status: "healthy", minutesAgo: 27 },
  { id: "berita_sulsel",   name: "BeritaSulsel",     tier: "A+", status: "healthy", minutesAgo: 14 },
  { id: "voice_sulawesi",  name: "Voice Sulawesi",   tier: "A",  status: "healthy", minutesAgo: 21 },
  { id: "new_domain_1",    name: "newspinrang123.id",tier: "UNREVIEWED", status: "unreviewed", minutesAgo: null },
];

export const MOCK_TRENDING = [
  { id: "tt_lpg",    topic: "Distribusi LPG 3 Kg",     count: 87, category: "ESDM & Energi",  isCritical: true  },
  { id: "tt_solar",  topic: "Solar Subsidi & APMS",    count: 62, category: "ESDM & Energi",  isCritical: true  },
  { id: "tt_pangan", topic: "Harga Pangan & Inflasi",  count: 45, category: "Perdagangan",    isCritical: false },
  { id: "tt_pasar",  topic: "Operasi Pasar Murah",     count: 38, category: "Perdagangan",    isCritical: false },
  { id: "tt_ikm",    topic: "IKM & UMKM",              count: 24, category: "Perindustrian",  isCritical: false },
];
