// Seed Firestore - Direktori Pasar Kabupaten Pinrang
// Generated 2026-08-28
const markets = [
  {
    "id": "pasar-sentral-pinrang",
    "slug": "pasar-sentral-pinrang",
    "nama": "Pasar Sentral Pinrang",
    "namaAlternatif": "",
    "kecamatan": "Watang Sawitto",
    "desaKelurahan": "Penrang",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "tinggi",
    "buktiOperasionalTerakhir": "Aktivitas publik terkonfirmasi 2025; kawasan Pasar Sentral juga muncul pada pekerjaan jalan Pemkab Agustus 2026.",
    "klasifikasiPerda2017": "A",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah II",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Status aktif aman ditampilkan. Data kios/los/pedagang menunggu data internal terbaru.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": true,
    "sumber": [
      {
        "judul": "Resmob Polres Pinrang Bekuk Pelaku Jambret",
        "instansi": "RRI",
        "tahun": 2025,
        "url": "https://rri.co.id/bone/regional/1464386/resmob-polres-pinrang-bekuk-pelaku-jambret"
      },
      {
        "judul": "Dinas BIMACIPTA Evaluasi Progres Pekerjaan Peningkatan Jalan",
        "instansi": "Pemkab Pinrang - Dinas BIMACIPTA",
        "tahun": 2026,
        "url": "https://disbimacipta.pinrangkab.go.id/index.php/publikasi/berita/dinas-bimacipta-evaluasi-progres-pekerjaan-peningkatan-jalan"
      }
    ]
  },
  {
    "id": "pasar-kampoeng-djaja",
    "slug": "pasar-kampoeng-djaja",
    "nama": "Pasar Kampoeng Djaja",
    "namaAlternatif": "Pasar Kampung Jaya",
    "kecamatan": "Watang Sawitto",
    "desaKelurahan": "Jaya",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "sedang",
    "buktiOperasionalTerakhir": "Keberadaan lokasi/nama terkonfirmasi 2025, tetapi bukti aktivitas jual-beli terbaru belum cukup kuat.",
    "klasifikasiPerda2017": "A",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah II",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Konfirmasi ke pengelola/UPTD sebelum badge Aktif.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": false,
    "sumber": [
      {
        "judul": "Rumah Dekat Pasar Kampung Jaya Nyaris Terbakar",
        "instansi": "Pijar News",
        "tahun": 2025,
        "url": "https://pijarnews.com/bikin-panik-hingga-gemetar-rumah-dekat-pasar-kampung-jaya-nyaris-terbakar/"
      }
    ]
  },
  {
    "id": "pasar-bungi",
    "slug": "pasar-bungi",
    "nama": "Pasar Bungi",
    "namaAlternatif": "",
    "kecamatan": "Duampanua",
    "desaKelurahan": "Bungi",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "tinggi",
    "buktiOperasionalTerakhir": "Penelitian lapangan 2025 membahas pedagang aktif; pemberitaan November 2025 menyebut warga berjualan ke Pasar Bungi.",
    "klasifikasiPerda2017": "B",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [
      "Kamis",
      "Minggu"
    ],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Hari pasar sebaiknya tetap dikonfirmasi UPTD sebelum menjadi jadwal resmi.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": true,
    "sumber": [
      {
        "judul": "Pengaruh Lokasi Usaha dan Modal Usaha terhadap Tingkat Pendapatan Pedagang Pakaian di Pasar Bungi",
        "instansi": "IAIN Parepare",
        "tahun": 2025,
        "url": "https://repository.iainpare.ac.id/id/eprint/11685/"
      },
      {
        "judul": "Ditinggal Pergi Jualan ke Pasar, Rumah Warga Paku Dibobol Maling",
        "instansi": "Radar Sulbar",
        "tahun": 2025,
        "url": "https://radarsulbar.fajar.co.id/2025/11/13/ditinggal-pergi-jualan-ke-pasar-rumah-warga-paku-dibobol-maling/"
      }
    ]
  },
  {
    "id": "pasar-pekkabata",
    "slug": "pasar-pekkabata",
    "nama": "Pasar Pekkabata",
    "namaAlternatif": "",
    "kecamatan": "Duampanua",
    "desaKelurahan": "Pekkabata",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "tinggi",
    "buktiOperasionalTerakhir": "DPRD membahas pengelola/sampah pasar pada 2025; polisi menyebut transaksi jual-beli emas di Pasar Pekkabata pada 2026.",
    "klasifikasiPerda2017": "B",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Hari pasar belum dimasukkan karena sumber daring tidak konsisten.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": true,
    "sumber": [
      {
        "judul": "RDP DPRD Pinrang terkait sampah di Pekkabata",
        "instansi": "Mata Lasinrang",
        "tahun": 2025,
        "url": "https://www.matalasinrang.com/komisi-iii-dprd-pinrang-gelar-rapat-dengar-pendapat-terkait-sampah-di-pekkabata-duampanua/"
      },
      {
        "judul": "Kronologi 2 Pria Curi Brankas Isi 1 Kg Emas di Pinrang",
        "instansi": "detikSulsel",
        "tahun": 2026,
        "url": "https://www.detik.com/sulsel/hukum-dan-kriminal/d-8459899/kronologi-2-pria-curi-brankas-isi-1-kg-emas-di-pinrang-intai-korban-di-pasar"
      }
    ]
  },
  {
    "id": "pasar-cempa",
    "slug": "pasar-cempa",
    "nama": "Pasar Cempa",
    "namaAlternatif": "",
    "kecamatan": "Cempa",
    "desaKelurahan": "Cempa",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "sedang",
    "buktiOperasionalTerakhir": "Kawasan Cempa Pasar masih digunakan sebagai nama lokasi pada 2025; bukti transaksi pasar terbaru yang eksplisit belum cukup.",
    "klasifikasiPerda2017": "B",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Konfirmasi operasional 2026 ke UPTD.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": false,
    "sumber": [
      {
        "judul": "BAZNAS Kabupaten Pinrang Ringankan Beban Lima Mustahik",
        "instansi": "BAZNAS Kabupaten Pinrang",
        "tahun": 2025,
        "url": "https://kabpinrang.baznas.go.id/berita/news-show/baznas-kabupaten-pinrang-ringankan-beban-lima-mustahik-di-momentum-maulid-nabi-muhammad-saw/26345"
      },
      {
        "judul": "Persiapkan Pojok Pajak, Pajak Pinrang Tinjau Pasar",
        "instansi": "Direktorat Jenderal Pajak",
        "tahun": 2022,
        "url": "https://www.pajak.go.id/id/berita/persiapkan-pojok-pajak-pajak-pinrang-tinjau-pasar"
      }
    ]
  },
  {
    "id": "pasar-leppangang",
    "slug": "pasar-leppangang",
    "nama": "Pasar Leppangang",
    "namaAlternatif": "",
    "kecamatan": "Patampanua",
    "desaKelurahan": "Leppangang",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "rendah",
    "buktiOperasionalTerakhir": "Nama pasar tercantum dalam Perda 2017 dan dokumen pengelola lama; bukti operasional 2025–2026 belum ditemukan.",
    "klasifikasiPerda2017": "B",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Lokasi dan status operasional perlu verifikasi internal.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": false,
    "sumber": []
  },
  {
    "id": "pasar-langnga",
    "slug": "pasar-langnga",
    "nama": "Pasar Langnga",
    "namaAlternatif": "Pasar Tradisional Langnga",
    "kecamatan": "Mattiro Sompe",
    "desaKelurahan": "Pallameang",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "tinggi",
    "buktiOperasionalTerakhir": "Polri melakukan pengamanan pasar saat aktivitas jual-beli pada 2025.",
    "klasifikasiPerda2017": "B",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [
      "Rabu",
      "Sabtu"
    ],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Status aktif kuat; jadwal sebaiknya dikonfirmasi UPTD.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": true,
    "sumber": [
      {
        "judul": "Pengamanan di Pasar Tradisional Langnga",
        "instansi": "Tribratanews Polda Sulsel",
        "tahun": 2025,
        "url": "https://tribratanews.sulsel.polri.go.id/bhabinkamtibmas-kelurahan-pallameang-laksanakan-patroli-dan-pengamanan-di-pasar-tradisional-langnga/"
      }
    ]
  },
  {
    "id": "pasar-teppo",
    "slug": "pasar-teppo",
    "nama": "Pasar Teppo",
    "namaAlternatif": "Pasar Tradisional Teppo",
    "kecamatan": "Patampanua",
    "desaKelurahan": "Benteng",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "tinggi",
    "buktiOperasionalTerakhir": "Penelitian 2025 dilakukan langsung terhadap perempuan pedagang Pasar Tradisional Teppo.",
    "klasifikasiPerda2017": "B",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [
      "Kamis",
      "Minggu"
    ],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Kelurahan Benteng terkonfirmasi dari penelitian 2025; jadwal perlu konfirmasi administratif.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": true,
    "sumber": [
      {
        "judul": "Strategi Nafkah Perempuan Pedagang di Pasar Tradisional Teppo",
        "instansi": "IAIN Parepare",
        "tahun": 2025,
        "url": "https://repository.iainpare.ac.id/id/eprint/12555/"
      }
    ]
  },
  {
    "id": "pasar-kariango",
    "slug": "pasar-kariango",
    "nama": "Pasar Kariango",
    "namaAlternatif": "",
    "kecamatan": "Mattiro Bulu",
    "desaKelurahan": "Pananrang",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "tinggi",
    "buktiOperasionalTerakhir": "Penelitian 2025 melakukan wawancara pedagang di Pasar Kariango; data Kementerian ESDM Januari 2026 mencantumkan alamat Pasar Kariango, Desa Pananrang.",
    "klasifikasiPerda2017": "B",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah II",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [
      "Selasa",
      "Jumat"
    ],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Jadwal perlu konfirmasi UPTD sebelum menjadi jadwal resmi.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": true,
    "sumber": [
      {
        "judul": "Analisis Hukum Ekonomi Syariah terhadap Transaksi Tukar Tambah Emas di Pasar Kariango",
        "instansi": "IAIN Parepare",
        "tahun": 2025,
        "url": "https://repository.iainpare.ac.id/id/eprint/10933/"
      },
      {
        "judul": "Data Subpenyalur LPG 3 Kg Sulawesi Selatan Januari 2026",
        "instansi": "Kementerian ESDM",
        "tahun": 2026,
        "url": "https://migas.esdm.go.id/cms/uploads/informasi-publik/Penyalur%20LPG%203KG/2026%20-%20Penyalur%20LPG%20Januari/2026%20-%20Januari%20-%20Subpenyalur%20-%20SULAWESI%20SELATAN.pdf"
      }
    ]
  },
  {
    "id": "pasar-marawi",
    "slug": "pasar-marawi",
    "nama": "Pasar Marawi",
    "namaAlternatif": "",
    "kecamatan": "Tiroang",
    "desaKelurahan": "Marawi",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "rendah",
    "buktiOperasionalTerakhir": "Nama pasar tercantum dalam Perda 2017 dan dokumen pengelola lama, tetapi bukti operasional terbaru belum cukup.",
    "klasifikasiPerda2017": "B",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah II",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Prioritas verifikasi lapangan/UPTD.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": false,
    "sumber": []
  },
  {
    "id": "pasar-lanrisang",
    "slug": "pasar-lanrisang",
    "nama": "Pasar Lanrisang",
    "namaAlternatif": "Pasar Jampue (perlu konfirmasi apakah objek yang sama)",
    "kecamatan": "Lanrisang",
    "desaKelurahan": "",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "rendah",
    "buktiOperasionalTerakhir": "Perda 2017 menyebut Pasar Lanrisang; nomenklatur Jampue muncul pada data lama dan perlu dikonfirmasi sebelum disatukan.",
    "klasifikasiPerda2017": "C",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah II",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Pastikan nama aset/lokasi dari UPTD atau KIB.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": false,
    "sumber": []
  },
  {
    "id": "pasar-suppa",
    "slug": "pasar-suppa",
    "nama": "Pasar Suppa",
    "namaAlternatif": "Pasar Rakyat Suppa",
    "kecamatan": "Suppa",
    "desaKelurahan": "",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "tinggi",
    "buktiOperasionalTerakhir": "Bukti eksplisit terakhir yang ditemukan: 8 Maret 2022 Pasar Rakyat Suppa sepi tanpa penjual/pembeli. Belum ada bukti kuat 2025–2026 bahwa objek yang sama telah aktif kembali.",
    "klasifikasiPerda2017": "C",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah II",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Bedakan dari pasar lain di Kecamatan Suppa, misalnya Pasar Ujung Lero.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": false,
    "sumber": [
      {
        "judul": "2 Pasar Pinrang Jadi Proyek Mubazir-Habiskan Rp 29 M",
        "instansi": "detikSulsel",
        "tahun": 2022,
        "url": "https://www.detik.com/sulsel/berita/d-5973605/2-pasar-pinrang-jadi-proyek-mubazir-habiskan-rp-29-m-dprd-desak-solusi-pemda"
      }
    ]
  },
  {
    "id": "pasar-malimpung",
    "slug": "pasar-malimpung",
    "nama": "Pasar Malimpung",
    "namaAlternatif": "",
    "kecamatan": "Patampanua",
    "desaKelurahan": "Malimpung",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "sedang",
    "buktiOperasionalTerakhir": "Dokumen KPU 2024 berulang kali menggunakan 'depan Pasar Malimpung' sebagai titik lokasi; aktivitas pasar 2026 tetap perlu konfirmasi.",
    "klasifikasiPerda2017": "C",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Keberadaan lokasi kuat, status aktivitas 2026 perlu konfirmasi.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": false,
    "sumber": [
      {
        "judul": "Keputusan KPU Kabupaten Pinrang Nomor 755 Tahun 2024",
        "instansi": "KPU Kabupaten Pinrang",
        "tahun": 2024,
        "url": "https://jdih.kpu.go.id/data-kabko/pinrang/data_kepkpud/755-SK%20SALINAN%20PERUBAHAN%20LOKASI%20APK%20DAN%20JADWAL%20RAPAT%20UMUM%20KPU%20PINRANG.pdf"
      }
    ]
  },
  {
    "id": "pasar-labolong",
    "slug": "pasar-labolong",
    "nama": "Pasar Labolong",
    "namaAlternatif": "",
    "kecamatan": "Mattiro Sompe",
    "desaKelurahan": "Mattongang-Tongang / Dusun Labolong",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "rendah",
    "buktiOperasionalTerakhir": "Nama pasar tercantum dalam Perda 2017 dan dokumen pengelola lama; data operasional terbaru belum ditemukan.",
    "klasifikasiPerda2017": "C",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Alamat dusun/desa perlu dicocokkan dengan dokumen aset/UPTD.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": false,
    "sumber": []
  },
  {
    "id": "pasar-tuppu",
    "slug": "pasar-tuppu",
    "nama": "Pasar Tuppu",
    "namaAlternatif": "Pasar Tradisional Tuppu",
    "kecamatan": "Lembang",
    "desaKelurahan": "Tuppu",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "perlu-verifikasi",
    "statusLabel": "Perlu Verifikasi",
    "tingkatKeyakinanStatus": "sedang",
    "buktiOperasionalTerakhir": "Nama dan fungsi historis pasar terdokumentasi, tetapi bukti operasional 2025–2026 belum cukup.",
    "klasifikasiPerda2017": "C",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [
      "Selasa",
      "Jumat"
    ],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Hari pasar adalah data terdahulu; jangan tampilkan sebagai jadwal resmi sebelum konfirmasi 2026.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": false,
    "sumber": []
  },
  {
    "id": "pasar-pajalele",
    "slug": "pasar-pajalele",
    "nama": "Pasar Pajalele",
    "namaAlternatif": "",
    "kecamatan": "Lembang",
    "desaKelurahan": "Binanga Karaeng / Dusun Pajalele",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "aktif",
    "statusLabel": "Aktif",
    "tingkatKeyakinanStatus": "tinggi",
    "buktiOperasionalTerakhir": "Penelitian lapangan terbit Mei 2025 menyebut Pasar Pajalele berlangsung Rabu dan Sabtu dengan pedagang aktif.",
    "klasifikasiPerda2017": "C",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah I",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [
      "Rabu",
      "Sabtu"
    ],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Status aktif kuat berdasarkan penelitian lapangan 2025.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": true,
    "sumber": [
      {
        "judul": "Jurnal Agroterpadu Volume 4 Nomor 2, Mei 2025",
        "instansi": "Universitas Al Asyariah Mandar",
        "tahun": 2025,
        "url": "https://journal.lppm-unasman.ac.id/index.php/agroterpadu/article/download/3942/pdf"
      }
    ]
  },
  {
    "id": "pasar-paleteang",
    "slug": "pasar-paleteang",
    "nama": "Pasar Paleteang",
    "namaAlternatif": "Pasar Inpres Paleteang (nama dikenal; nomenklatur aset perlu verifikasi)",
    "kecamatan": "Paleteang",
    "desaKelurahan": "Temmassarangnge / kawasan Kompleks Pasar Paleteang",
    "alamat": "",
    "latitude": null,
    "longitude": null,
    "statusOperasional": "tidak-aktif",
    "statusLabel": "Tidak Aktif",
    "tingkatKeyakinanStatus": "tinggi",
    "buktiOperasionalTerakhir": "Masih tercantum normatif dalam Perda 2017, tetapi bukti operasional/statistik berikutnya menunjukkan pasar lama tidak lagi berfungsi sebagai pasar aktif.",
    "klasifikasiPerda2017": "A",
    "catatanKlasifikasi": "Klasifikasi berdasarkan Perda Kabupaten Pinrang Nomor 2 Tahun 2017; jangan diperlakukan otomatis sebagai klasifikasi operasional 2026.",
    "unitPengelola": "UPTD Pasar Wilayah II",
    "statusVerifikasiUnitPengelola": "perlu-konfirmasi-internal-2026",
    "hariPasar": [],
    "jamOperasional": "",
    "jumlahKios": null,
    "jumlahLos": null,
    "jumlahPedagang": null,
    "luasLahanM2": null,
    "komoditasUtama": [],
    "fasilitas": [],
    "fotoUtama": "",
    "galeri": [],
    "deskripsi": "",
    "sejarahSingkat": "",
    "catatanVerifikasi": "Tampilkan badge Tidak Aktif. 'Tipe A' hanya konteks Perda 2017/historis. Istilah Pasar Inpres Paleteang jangan dijadikan nama resmi aset tanpa KIB/SK aset.",
    "tahunData": 2026,
    "tanggalVerifikasi": "2026-08-28",
    "published": true,
    "showAsActive": false,
    "sumber": [
      {
        "judul": "Evaluasi Pengadaan Terminal dalam Perda Kabupaten Pinrang",
        "instansi": "IAIN Parepare",
        "tahun": 2020,
        "url": "https://repository.iainpare.ac.id/id/eprint/1540/1/15.2600.004.pdf"
      }
    ]
  }
];

async function seedMarkets(db, helpers) {
  const { doc, setDoc, collection } = helpers;
  for (const market of markets) {
    const ref = doc(collection(db, 'markets'), market.id);
    await setDoc(ref, market, { merge: true });
    console.log('Seeded:', market.id);
  }
}

export { markets, seedMarkets };
